apiVersion: apps/v1
kind: Deployment
metadata:
  name: xds-client
  labels:
    app: xds-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xds-client
  template:
    metadata:
      labels:
        app: xds-client
    spec:
      containers:
      - name: xds-client
        image: xds-client:1.0
        ports:
        - containerPort: 8088
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8088
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8088
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: xds-client
spec:
  selector:
    app: xds-client
  ports:
  - port: 8088
    targetPort: 8088
  type: ClusterIP 